from enum import IntEnum

class StandID(IntEnum):
    GROUP = 0x70
    KEEP_ALIVE = 0x02
    TELEMETRY = 0x03
    SET_THROTTLE = 0x04

    ENABLE_SPIN = 0x06

    DISABLE_SPIN = 0x08

    DIRECTION_NORMAL = 0x10

    DIRECTION_REVERSE = 0x12

    SERVICE_CMD = 0x14
    SERVICE_CMD_ANS = 0x15

    SET_THROTTLE_CHANNEL = 0x16

    SET_CALIBRATIONS = 0x20
    SET_CALIBRATIONS_ANS = 0x21

    GET_CALIBRATIONS = 0x22
    GET_CALIBRATIONS_ANS = 0x23

    SET_OPTIONS = 0x30
    SET_OPTIONS_ANS = 0x31

    GET_OPTIONS = 0x32
    GET_OPTIONS_ANS = 0x33

    DFU = 0x90

STAND_GROUP = 0x70

STAND_KEEP_ALIVE = 0x02
STAND_TELEMETRY = 0x03
STAND_SET_THROTTLE =0x04

STAND_ENABLE_SPIN = 0x06

STAND_DISABLE_SPIN = 0x08

STAND_DIRECTION_NORMAL = 0x10

STAND_DIRECTION_REVERSE = 0x12

STAND_SET_CALIBRATIONS = 0x20
STAND_SET_CALIBRATIONS_ANS = 0x21

STAND_GET_CALIBRATIONS = 0x22
STAND_GET_CALIBRATIONS_ANS = 0x23

MODULE_STAND_SET_OPTIONS = 0x30
MODULE_STAND_SET_OPTIONS_ANS = 0x31

MODULE_STAND_GET_OPTIONS =0x32
MODULE_STAND_GET_OPTIONS_ANS = 0x33

STAND_DFU = 0x90

# ---------------------Flash---------------------
PACKET_FLASH_MODULE = 0x00
PACKET_FLASH_MODULE_ENTER_UPD = 0x24
PACKET_FLASH_MODULE_RESET = 0x26
# --------------------Connection--------------------
PACKET_CONNECTION_MODULE = 0x01
PACKET_CONNECTION_MODULE_GET_FIRMWARE_STR_NAME = 0x0C                 # запрос строки содержащей название и версию прошивки
PACKET_CONNECTION_MODULE_GET_FIRMWARE_STR_NAME_ANS = 0x0D                 # ответ на запрос строки содержащей название и версию прошивки
